# Template PHP Build

# This template allows you to validate your PHP application.
# The workflow allows running tests and code linting on the default branch.

image: php:7.4.3


pipelines:
  default:
        - step:
            script:
              - apt-get update && apt-get install -y unzip
              - apt-get install -y openssh-client
              - ssh root@208.91.189.29 'bash -s' < execute.sh